#ifndef FORTUNES_HPP
# define FORTUNES_HPP

# define VECTOR "https://www.youtube.com/watch?v=bOIe0DIMbI8&ab_channel=DSchnell"

const char *fortunes[] = {
"A dream you have will come true.",
"A good way to keep healthy is to eat more Chinese food.",
"A journey of a thousand miles begins with a single step.",
"A new voyage will fill your life with untold memories.",
"A short stranger will soon enter your life with blessings to share.",
"A stranger, is a friend you have not spoken to yet.",
"A thrilling time is in your immediate future.",
"A very attractive person has a message for you.",
"About time I got out of that cookie.",
"Accept your past without regrets. Handle your present with confidence. Face your future without fear.",
"Adversity is the parent of virtue.",
"An upward movement initiated in time can counteract fate.",
"Ask yourself if what you are doing today is getting you closer to where you want to be tomorrow.",
"Come back later, I am sleeping. Yes cookies need their sleep too.",
"Could I get some directions? To Where? To your heart.",
"Everyone agrees. You are the best.",
"Fortune favors the brave.",
"Fortune Not Found: Abort, Retry, Ignore?",
"Happiness is an activity.",
"Hearty laughter is a god way to jog internally without having to go outdoors.",
"If winter comes, can spring be far behind?",
"If you feel you are right, stand firmly by your convictions.",
"If you have something worth fighting for, then fight for it.",
"It is easier to resist at the beginning than at the end.",
"It is now, and in this world, that we must live.",
"Its amazing how much good you can do if you don’t care who gets the credit.",
"It’s better to be alone sometimes.",
"Jealousy doesn’t open doors, it closes them.",
"Joys are often the shadows, cast by sorrows.",
"Keep your eye out for someone special.",
"Let the deeds speak.",
"Love can last a lifetime, if you want it to.",
"Never give up. Always find a reason to keep trying.",
"Never give up. You’re not a failure if you don’t give up.",
"No gift to your mother can ever equal her gift to you – life.",
"Nothing astonishes men so much as common sense and plain dealing.",
"Now is the time to try something new.",
"Now would be a good time to take up a new sport.",
"Our deeds determine us, as much as we determine our deeds.",
"Relationships.",
"Serious trouble will bypass you.",
"Sometimes you just need to lay on the floor.",
"Stay true to those who would do the same for you.",
"Stop wishing. Start doing.",
"The greatest risk is not taking one.",
"The love of your life is stepping into your planet this summer.",
"The man on the top of the mountain did not fall there.",
"There is no greater pleasure than seeing your loved ones prosper.",
"There’s no such think as an ordinary cat.",
"Wealth awaits you very soon.",
"When fear hurts you, conquer it and defeat it.",
"When you squeeze an orange, orange juice comes out because that’s what’s inside.",
"Wouldn’t it be ironic to die in the living room?",
"You already know the answer to the questions lingering inside your head.",
"You are very talented in many ways.",
"You can make your own happiness.",
"You laugh now, wait till you get home.",
"You must try, or hate yourself for not trying.",
"Your high-minded principles spell success.",
"You will be called in to fulfill a position of high honor and responsibility.",
"You will be hungry again in one hour.",
"You will become great if you believe in yourself.",
"You will conquer obstacles to achieve success.",
"You will marry your lover.",
"You will travel to many exotic places in your lifetime.",
"Your ability for accomplishment will follow with success.",
"Your resemblance to a muppet will prevent the world from taking you seriously.",
};

#endif
